---
image: ghcr.io/astral-sh/uv:python3.8-alpine

pages:
  stage: deploy
  before_script:
    - uv --version
  script:
    - uv sync
    # - uv run pelican
    - uv run pelican -s publishconf.py
  artifacts:
    paths:
      - output
  publish: output
  only:
    - main
