---

image: ghcr.io/astral-sh/uv:python3.8-alpine

test:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  before_script:
    - uv --version
  script:
    - uv sync
    - uv run pelican --fatal errors
  artifacts:
    paths:
      - output

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - uv --version
  script:
    - uv sync
    - uv run pelican -s publishconf.py
  artifacts:
    paths:
      - output
  publish: output
